### ISSUE TITLE
Not connected to websocket

### ISSUE THREAD

**Issue by newcanopies** [flynneva/flynn-labs#127]
Hi, is this the intended display? (ros2-web-bridge is running)
![image](https://user-images.githubusercontent.com/65022111/115849663-64fd5000-a425-11eb-989b-e6cccb35d6a9.png)

**Comment by flynneva** [comment]
hello @newcanopies! well...sort of i guess.

I probably should have some sort of "demo" running, but that tab is actually meant for connecting to and debugging ROS robots that are running rosbridge.  it should be able to visualize a pointcloud if a pointcloud topic is available. if you have experience with ROS and can run the [ros pointcloud example](https://github.com/ros/ros_tutorials/commit/74cc182dce2bb7d221052d1d45fe4ad0e7705843) I helped write, then you should be able to visualize it there after running [ros_bridge](http://wiki.ros.org/rosbridge_suite)

not sure if ill have any time this week or next but ill keep you posted on this issue if I end up implementing a "demo" for people who dont have a robot/ROS node to connect to.

**Comment by flynneva** [comment]
the 3D visualizer is just a package I wrote called `react-ros-three` - meant for visualizing ROS data. 

there are some examples in the documentation I think:
https://flynneva.github.io/react-ros-three/readme

**Comment by newcanopies** [comment]
the interesting thing to me was that I am running headless gzserver and ros2-web-bridge on localhost:9090 
but this web-client wasn't able to connect to that websocket - which could be for a host of reasons.

is this web-client hyper-specific [ros pointcloud example ](https://github.com/ros/ros_tutorials/commit/74cc182dce2bb7d221052d1d45fe4ad0e7705843)?

nice work!

**Comment by flynneva** [comment]
the 3D visualizer only will work for a pointcloud2 topic right now since that's all I've wrote so far for it.

The drop down menu and ros-client should work for any message type though.

Try out some of the demos for react-ros (the package that this flynnlabs website uses) and see if it works there? I haven't tried it yet with the ROS2 web bridge...but maybe it isn't compatible? It should be I feel like.

https://github.com/flynneva/react-ros

**Comment by flynneva** [comment]
also I forgot to add it works on any pointcloud2 topic - not just the demo pointcloud - as long as it's connected, selected and publishing.

I've ran it live for some lidar sensors I work on and it works fine.

**Comment by newcanopies** [comment]
Interesting use of `roslib` dependency as opposed to` roslibjs`, is that why you choose **react** as wrapper? @flynneva 

> Try out some of the demos for react-ros (the package that this flynnlabs website uses) and see if it works there? I haven't tried it yet with the ROS2 web bridge...but maybe it isn't compatible? It should be I feel like.
> 
> https://github.com/flynneva/react-ros

I tried to test compatibility with  `ros2-web-bridge`  running, but only got this far: (site couldn't be reached)
![image](https://user-images.githubusercontent.com/65022111/115833101-f5329980-a413-11eb-86a1-9b4dd99e976e.png)
![image](https://user-images.githubusercontent.com/65022111/115849086-d5f03800-a424-11eb-88da-d7049644e9fb.png)


ps. perhaps change [README](https://github.com/flynneva/react-ros#install) instructions from `npm install react-ros`  to `npm install`  :)
<details>

```
npm ERR! code ENOSELF  

npm ERR! Refusing to install package with name "react-ros" under a package  

npm ERR! also called "react-ros". Did you name your project the same    

npm ERR! as the dependency you're installing?    

npm ERR!   

npm ERR! For more information, see:   
 
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
```

</details>

**Comment by flynneva** [comment]
I'll work on updating this over the weekend. Thanks for testing it out! Could you make an issue on that repo for any issues you run into?

**Comment by newcanopies** [comment]
what was the driver to use `react` ?

**Comment by flynneva** [comment]
well it seemed very flexible and user friendly and seemed to have a bunch of tutorials out there.
